<?php
namespace Inanimatt\SiteBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-28 at 10:00:15.
 */
class SiteBuilderTemplateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SiteBuilderTemplate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SiteBuilderTemplate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Inanimatt\SiteBuilder\SiteBuilderTemplate::__set
     * @covers Inanimatt\SiteBuilder\SiteBuilderTemplate::__get
     */
    public function testGetSet()
    {
        $this->object->test = 'Lorem ipsum';
        $this->assertEquals($this->object->test, 'Lorem ipsum', 'Can get and set a template variable');
        $this->assertNull($this->object->__get('nonexistent'), 'Nonexistent vars return null');
    }

    /**
     * @covers Inanimatt\SiteBuilder\SiteBuilderTemplate::__getVars
     * @covers Inanimatt\SiteBuilder\SiteBuilderTemplate::__setVars
     */
    public function testGetSetVars()
    {
        $test_array = array('lorem' => 'ipsum', 'dolor' => 'sit');
        $this->object->__setVars($test_array);
        $result = $this->object->__getVars();

        $this->assertEquals($test_array, $result, 'Can get/set template variables in bulk');
    }

    /**
     * @expectedException Inanimatt\SiteBuilder\Exception\RenderException
     */
    public function testRenderException()
    {
        $this->object->render('nosuchfile.php');
    }

    /**
     * @expectedException Inanimatt\SiteBuilder\Exception\ArgumentException
     */
    public function test__SetVarsException()
    {
        $this->object->__setVars('invalid');
    }

    /**
     * @expectedException Inanimatt\SiteBuilder\Exception\ArgumentException
     */
    public function test__SetException()
    {
        $a = array('thing', 'stuff');
        $this->object->__set($a, 'test');
    }

    /**
     * @expectedException Inanimatt\SiteBuilder\Exception\ArgumentException
     */
    public function test__getException()
    {
        $a = array('thing', 'stuff');
        $this->object->__get($a);
    }

}
