<?php
namespace Inanimatt\SiteBuilder\ContentHandler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-21 at 00:59:50.
 */
class PhpFileContentHandlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PhpFileContentHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PhpFileContentHandler(__DIR__.'/../../../resources/subdir/example.php', 'subdir', 'subdir/example.php' );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Inanimatt\SiteBuilder\ContentHandler\PhpFileContentHandler::getName
     */
    public function testGetName()
    {
        $this->assertEquals($this->object->getName(), 'subdir/example.php');
    }

    /**
     * @covers Inanimatt\SiteBuilder\ContentHandler\PhpFileContentHandler::getContent
     */
    public function testGetContent()
    {
        $content = '
<h1>Hello World</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>';

        $this->assertEquals($content, $this->object->getContent());
    }

    /**
     * @covers Inanimatt\SiteBuilder\ContentHandler\PhpFileContentHandler::getMetadata
     */
    public function testGetMetadata()
    {
        $this->assertTrue(is_array($this->object->getMetadata()));
        $this->assertArrayHasKey('title', $this->object->getMetadata());
        $this->assertArrayHasKey('content', $this->object->getMetadata());
        
    }
}
