<?php
namespace Inanimatt\SiteBuilder\Renderer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-26 at 00:31:03.
 */
class PhpRendererTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PhpRenderer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PhpRenderer(__DIR__.'/../../../resources/');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Inanimatt\SiteBuilder\Renderer\PhpRenderer::render
     * @covers Inanimatt\SiteBuilder\Renderer\PhpRenderer::__construct
     */
    public function testRender()
    {
        $result = $this->object->render(array('title' => 'Lorem', 'content' => 'Lorem ipsum'), 'template.php');
        $this->assertEquals('<title>Lorem</title><content>Lorem ipsum</content>', $result);
    }
}
